/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Local Session */
    get: operations['local_session_api_session_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_api_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/models': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Models */
    get: operations['models_api_models_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/brands': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Brands */
    get: operations['list_brands_api_brands_get'];
    put?: never;
    /** Create Brand */
    post: operations['create_brand_api_brands_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/brands/{brand_id}/attachments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Brand References */
    get: operations['brand_references_api_brands__brand_id__attachments_get'];
    put?: never;
    /** Attach Brand */
    post: operations['attach_brand_api_brands__brand_id__attachments_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/brands/{brand_id}/attachments/{artifact_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Brand Attachment */
    get: operations['brand_attachment_api_brands__brand_id__attachments__artifact_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Investigations */
    get: operations['list_investigations_api_investigations_get'];
    put?: never;
    /** Create Investigation */
    post: operations['create_investigation_api_investigations_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Investigation */
    get: operations['get_investigation_api_investigations__investigation_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Investigation */
    patch: operations['patch_investigation_api_investigations__investigation_id__patch'];
    trace?: never;
  };
  '/api/investigations/{investigation_id}/submissions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Submission */
    post: operations['add_submission_api_investigations__investigation_id__submissions_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/notes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Note */
    post: operations['add_note_api_investigations__investigation_id__notes_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/decisions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Decision */
    post: operations['add_decision_api_investigations__investigation_id__decisions_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/attachments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Attach Investigation */
    post: operations['attach_investigation_api_investigations__investigation_id__attachments_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/attachments/{artifact_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Investigation Attachment */
    get: operations['investigation_attachment_api_investigations__investigation_id__attachments__artifact_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Job */
    post: operations['create_job_api_investigations__investigation_id__jobs_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/jobs/{job_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Job */
    get: operations['get_job_api_jobs__job_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/jobs/{job_id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel Job */
    post: operations['cancel_job_api_jobs__job_id__cancel_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/groups': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Groups */
    get: operations['groups_api_investigations__investigation_id__groups_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/entities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Entities */
    get: operations['entities_api_investigations__investigation_id__entities_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/graph': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Graph */
    get: operations['graph_api_investigations__investigation_id__graph_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/evidence/{evidence_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Evidence */
    get: operations['evidence_api_investigations__investigation_id__evidence__evidence_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/analyses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Analyses */
    get: operations['analyses_api_investigations__investigation_id__analyses_get'];
    put?: never;
    /** Create Analysis */
    post: operations['create_analysis_api_investigations__investigation_id__analyses_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/report': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Report */
    get: operations['report_api_investigations__investigation_id__report_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/evidence': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Evidence List */
    get: operations['evidence_list_api_investigations__investigation_id__evidence_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/captures': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Captures */
    get: operations['captures_api_investigations__investigation_id__captures_get'];
    put?: never;
    /** Create Capture */
    post: operations['create_capture_api_investigations__investigation_id__captures_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/visual-similarity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Visual Similarity */
    get: operations['visual_similarity_api_investigations__investigation_id__visual_similarity_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/candidates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Candidates */
    get: operations['candidates_api_investigations__investigation_id__candidates_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/runs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs */
    get: operations['runs_api_investigations__investigation_id__runs_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/changes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Changes */
    get: operations['changes_api_investigations__investigation_id__changes_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/grounding': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Claim Grounding */
    get: operations['claim_grounding_api_investigations__investigation_id__grounding_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/watches': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Watch List */
    get: operations['watch_list_api_investigations__investigation_id__watches_get'];
    put?: never;
    /** Create Watch */
    post: operations['create_watch_api_investigations__investigation_id__watches_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/watches/{watch_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Watch */
    patch: operations['patch_watch_api_investigations__investigation_id__watches__watch_id__patch'];
    trace?: never;
  };
  '/api/investigations/{investigation_id}/watches/{watch_id}/run': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run Watch */
    post: operations['run_watch_api_investigations__investigation_id__watches__watch_id__run_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/alerts/{alert_id}/read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Read Alert */
    post: operations['read_alert_api_investigations__investigation_id__alerts__alert_id__read_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/story/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Story Preview */
    post: operations['story_preview_api_investigations__investigation_id__story_preview_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/story/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Story Export */
    post: operations['story_export_api_investigations__investigation_id__story_export_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/memory': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Memory */
    get: operations['memory_api_investigations__investigation_id__memory_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/assistant': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** History */
    get: operations['history_api_investigations__investigation_id__assistant_get'];
    put?: never;
    /** Ask */
    post: operations['ask_api_investigations__investigation_id__assistant_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/replay/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview */
    post: operations['preview_api_investigations__investigation_id__replay_preview_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/investigations/{investigation_id}/replay/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Export */
    post: operations['export_api_investigations__investigation_id__replay_export_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Settings */
    get: operations['read_settings_api_settings_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Save Settings */
    patch: operations['save_settings_api_settings_patch'];
    trace?: never;
  };
  '/api/settings/llm/models': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Available Models */
    post: operations['available_models_api_settings_llm_models_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings/llm/test': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Test Llm */
    post: operations['test_llm_api_settings_llm_test_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings/sources/test': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Test Source */
    post: operations['test_source_api_settings_sources_test_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AnalysisCreate */
    AnalysisCreate: {
      /** Model Id */
      model_id?: string | null;
    };
    /** AnalysisPage */
    AnalysisPage: {
      /** Items */
      items: components['schemas']['AnalysisView'][];
      /** Next Cursor */
      next_cursor?: string | null;
      /** Total Unique */
      total_unique: number;
    };
    /** AnalysisView */
    AnalysisView: {
      /** Id */
      id: string;
      /** Status */
      status: string;
      /** Output */
      output: {
        [key: string]: unknown;
      };
      /** Model Id */
      model_id: string;
      /** Prompt Version */
      prompt_version: string;
      /** Snapshot Id */
      snapshot_id: string;
      /** Stale */
      stale: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Recorded Demo */
      recorded_demo: boolean;
      /** Metrics */
      metrics: {
        [key: string]: unknown;
      };
    };
    /** ArtifactView */
    ArtifactView: {
      /** Id */
      id: string;
      /** Sha256 */
      sha256: string;
      /** Mime */
      mime: string;
      /** Size Bytes */
      size_bytes: number;
      /** Investigation Id */
      investigation_id?: string | null;
      /** Brand Id */
      brand_id?: string | null;
      /** Submission Id */
      submission_id?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** AssessmentView */
    AssessmentView: {
      /**
       * Priority
       * @enum {string}
       */
      priority: 'normal' | 'review';
      /** Reasons */
      reasons: string[];
      /**
       * Automated Verdict
       * @enum {string}
       */
      automated_verdict: 'insufficient_evidence' | 'candidate' | 'likely_phishing';
      /**
       * Version
       * @default assessment-v1
       */
      version: string;
    };
    /** AssistantRequest */
    AssistantRequest: {
      /** Message */
      message: string;
      /** Evidence Ids */
      evidence_ids?: string[];
    };
    /** AvailableModels */
    AvailableModels: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'error';
      /** Items */
      items?: components['schemas']['ModelInfo'][];
      /**
       * Message
       * @default
       */
      message: string;
      /** Code */
      code?: string | null;
    };
    /** Body_attach_brand_api_brands__brand_id__attachments_post */
    Body_attach_brand_api_brands__brand_id__attachments_post: {
      /** File */
      file: string;
    };
    /** Body_attach_investigation_api_investigations__investigation_id__attachments_post */
    Body_attach_investigation_api_investigations__investigation_id__attachments_post: {
      /** File */
      file: string;
      /** Submission Id */
      submission_id?: string | null;
    };
    /** BrandCreate */
    BrandCreate: {
      /** Name */
      name: string;
      /** Official Domains */
      official_domains?: string[];
    };
    /** BrandPage */
    BrandPage: {
      /** Items */
      items: components['schemas']['BrandView'][];
      /** Next Cursor */
      next_cursor?: string | null;
      /** Total Unique */
      total_unique: number;
    };
    /** BrandView */
    BrandView: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Official Domains */
      official_domains: string[];
    };
    /** CaptureCreate */
    CaptureCreate: {
      /** Url */
      url: string;
      /**
       * Profile
       * @default desktop
       * @enum {string}
       */
      profile: 'desktop' | 'mobile';
    };
    /** ConnectionResult */
    ConnectionResult: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'error';
      /** Message */
      message: string;
      /** Code */
      code?: string | null;
      /** Model Id */
      model_id?: string | null;
      /** Elapsed Ms */
      elapsed_ms?: number | null;
    };
    /** DecisionCreate */
    DecisionCreate: {
      /**
       * Value
       * @enum {string}
       */
      value: 'unreviewed' | 'confirmed_phishing' | 'benign' | 'needs_review';
      /**
       * Note
       * @default
       */
      note: string;
    };
    /** DecisionView */
    DecisionView: {
      /** Id */
      id: string;
      /**
       * Value
       * @enum {string}
       */
      value: 'unreviewed' | 'confirmed_phishing' | 'benign' | 'needs_review';
      /** Note */
      note: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** EntityPage */
    EntityPage: {
      /** Items */
      items: components['schemas']['EntityView'][];
      /** Next Cursor */
      next_cursor: string | null;
      /** Total Unique */
      total_unique: number;
    };
    /** EntityRefView */
    EntityRefView: {
      /**
       * Kind
       * @enum {string}
       */
      kind: 'url' | 'domain' | 'ip' | 'cert' | 'js_hash' | 'favicon_hash';
      /** Value */
      value: string;
    };
    /** EntityView */
    EntityView: {
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: 'url' | 'domain' | 'ip' | 'cert' | 'js_hash' | 'favicon_hash';
      /** Canonical Value */
      canonical_value: string;
      /**
       * Evidence Count
       * @default 0
       */
      evidence_count: number;
      /** Last Seen */
      last_seen?: string | null;
      /**
       * Has Capture
       * @default false
       */
      has_capture: boolean;
      /** Shared Signals */
      shared_signals?: string[];
      /** Priority Score */
      priority_score?: number | null;
    };
    /** EvidenceView */
    EvidenceView: {
      /** Id */
      id: string;
      /** Investigation Id */
      investigation_id: string;
      subject: components['schemas']['EntityRefView'];
      /** Kind */
      kind: string;
      /** Provider */
      provider: string;
      /** Source Ref */
      source_ref: string;
      /** Observed At */
      observed_at: string | null;
      /**
       * Retrieved At
       * Format: date-time
       */
      retrieved_at: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
    };
    /** GraphView */
    GraphView: {
      /** Nodes */
      nodes: components['schemas']['EntityView'][];
      /** Relations */
      relations: components['schemas']['RelationView'][];
      /** Has More */
      has_more: boolean;
      /** Next Cursor */
      next_cursor: string | null;
    };
    /** GroupPage */
    GroupPage: {
      /** Items */
      items: components['schemas']['GroupView'][];
      /** Next Cursor */
      next_cursor: string | null;
      /** Total Unique */
      total_unique: number;
      /** Total Groups */
      total_groups: number;
    };
    /** GroupView */
    GroupView: {
      /** Key */
      key: string;
      /**
       * Criterion
       * @enum {string}
       */
      criterion: 'observed_ip' | 'cert_sha256' | 'js_sha256';
      /** Label */
      label: string;
      /** Entity Count */
      entity_count: number;
      /** Evidence Ids */
      evidence_ids: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** IntegrationPatch */
    IntegrationPatch: {
      /** Active Llm */
      active_llm?: ('local' | 'anthropic' | 'openai' | 'gemini' | 'openrouter') | null;
      /** Llm */
      llm?: {
        [key: string]: components['schemas']['LlmDraft'];
      };
      /** Sources */
      sources?: {
        [key: string]: components['schemas']['SourceDraft'];
      };
    };
    /** IntegrationView */
    IntegrationView: {
      /**
       * Active Llm
       * @enum {string}
       */
      active_llm: 'local' | 'anthropic' | 'openai' | 'gemini' | 'openrouter';
      /** Llm */
      llm: {
        [key: string]: components['schemas']['LlmView'];
      };
      /** Sources */
      sources: {
        [key: string]: components['schemas']['SourceView'];
      };
      /** Read Only */
      read_only: boolean;
    };
    /** InvestigationCreate */
    InvestigationCreate: {
      /** Brand Id */
      brand_id: string;
      /** Title */
      title: string;
    };
    /** InvestigationPage */
    InvestigationPage: {
      /** Items */
      items: components['schemas']['InvestigationView'][];
      /** Next Cursor */
      next_cursor?: string | null;
      /** Total Unique */
      total_unique: number;
    };
    /** InvestigationPatch */
    InvestigationPatch: {
      /**
       * Workflow
       * @enum {string}
       */
      workflow: 'open' | 'closed';
    };
    /** InvestigationView */
    InvestigationView: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Brand Id */
      brand_id: string;
      /** Brand Name */
      brand_name: string;
      /**
       * Workflow
       * @enum {string}
       */
      workflow: 'open' | 'closed';
      /**
       * Disposition
       * @enum {string}
       */
      disposition: 'unreviewed' | 'confirmed_phishing' | 'benign' | 'needs_review';
      /**
       * Priority
       * @enum {string}
       */
      priority: 'normal' | 'review';
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /**
       * Entity Count
       * @default 0
       */
      entity_count: number;
      /**
       * Evidence Count
       * @default 0
       */
      evidence_count: number;
      /** Source */
      source?: string | null;
      /**
       * Demo
       * @default false
       */
      demo: boolean;
      /** Submissions */
      submissions?: components['schemas']['SubmissionView'][];
      /** Notes */
      notes?: components['schemas']['NoteView'][];
      /** Decisions */
      decisions?: components['schemas']['DecisionView'][];
      /** Attachments */
      attachments?: components['schemas']['ArtifactView'][];
      /** Jobs */
      jobs?: components['schemas']['JobView'][];
      assessment?: components['schemas']['AssessmentView'] | null;
    };
    /** JobCreate */
    JobCreate: {
      /**
       * Kind
       * @enum {string}
       */
      kind: 'collect' | 'expand';
      /** Entity Id */
      entity_id?: string | null;
      /** Limits */
      limits?: {
        [key: string]: unknown;
      } | null;
    };
    /** JobView */
    JobView: {
      /** Id */
      id: string;
      /** Investigation Id */
      investigation_id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: 'collect' | 'expand' | 'analysis' | 'capture';
      /**
       * Status
       * @enum {string}
       */
      status: 'queued' | 'running' | 'completed' | 'partial' | 'failed' | 'cancelled';
      /** Progress */
      progress: {
        [key: string]: unknown;
      };
      /** Limits */
      limits: {
        [key: string]: unknown;
      };
      /** Truncated */
      truncated: boolean;
      /** Error */
      error: string | null;
      /** Cancel Requested */
      cancel_requested: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** LlmCheck */
    LlmCheck: {
      /**
       * Provider
       * @enum {string}
       */
      provider: 'local' | 'anthropic' | 'openai' | 'gemini' | 'openrouter';
      settings?: components['schemas']['LlmDraft'];
    };
    /** LlmDraft */
    LlmDraft: {
      /** Api Key */
      api_key?: string | null;
      /** Clear Key */
      clear_key?: boolean | null;
      /** Model Id */
      model_id?: string | null;
      /** Timeout Seconds */
      timeout_seconds?: number | null;
      /** Base Url */
      base_url?: string | null;
      /** Backend */
      backend?: ('sglang' | 'llama.cpp' | 'openai_compatible') | null;
    };
    /** LlmView */
    LlmView: {
      /** Label */
      label: string;
      /** Docs Url */
      docs_url: string;
      /** Base Url */
      base_url: string;
      /** Backend */
      backend: string;
      /** Model Id */
      model_id: string;
      /** Timeout Seconds */
      timeout_seconds: number;
      /** Key Configured */
      key_configured: boolean;
    };
    /** ModelInfo */
    ModelInfo: {
      /** Id */
      id: string;
      /** Runtime Version */
      runtime_version?: string | null;
      /**
       * Text Supported
       * @default true
       */
      text_supported: boolean;
      /** Vision Supported */
      vision_supported?: boolean | null;
    };
    /** ModelPage */
    ModelPage: {
      /** Items */
      items: components['schemas']['ModelStatusView'][];
      /** Status */
      status: string;
    };
    /** ModelStatusView */
    ModelStatusView: {
      /** Status */
      status: string;
      /** Model Id */
      model_id?: string | null;
      /** Endpoint */
      endpoint?: string | null;
      /** Text Supported */
      text_supported: boolean;
      /** Vision Supported */
      vision_supported?: boolean | null;
      /** Message */
      message: string;
      /**
       * Recorded Demo
       * @default false
       */
      recorded_demo: boolean;
    };
    /** NoteCreate */
    NoteCreate: {
      /** Text */
      text: string;
    };
    /** NoteView */
    NoteView: {
      /** Id */
      id: string;
      /** Text */
      text: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** RelationView */
    RelationView: {
      /** Id */
      id: string;
      /** Src Id */
      src_id: string;
      /** Dst Id */
      dst_id: string;
      /** Kind */
      kind: string;
      /** Evidence Ids */
      evidence_ids: string[];
    };
    /** ReplayExportRequest */
    ReplayExportRequest: {
      /** Preview Id */
      preview_id: string;
      /**
       * Redact
       * @default true
       */
      redact: boolean;
    };
    /** ReplayPreviewRequest */
    ReplayPreviewRequest: {
      /**
       * Redact
       * @default true
       */
      redact: boolean;
    };
    /** SourceCheck */
    SourceCheck: {
      /** Provider */
      provider: string;
      settings?: components['schemas']['SourceDraft'];
    };
    /** SourceDraft */
    SourceDraft: {
      /** Enabled */
      enabled?: boolean | null;
      /** Api Key */
      api_key?: string | null;
      /** Clear Key */
      clear_key?: boolean | null;
      /** File Path */
      file_path?: string | null;
      /** Mode */
      mode?: ('api' | 'local') | null;
    };
    /** SourceView */
    SourceView: {
      /** Label */
      label: string;
      /** Group */
      group: string;
      /** Description */
      description: string;
      /** Docs Url */
      docs_url: string | null;
      /** Enabled */
      enabled: boolean;
      /** Accepts Key */
      accepts_key: boolean;
      /** Key Configured */
      key_configured: boolean;
      /** File Path */
      file_path: string;
      /** Mode */
      mode: string;
    };
    /** StoryCreate */
    StoryCreate: {
      /** Evidence Ids */
      evidence_ids?: string[];
      /**
       * Redact
       * @default true
       */
      redact: boolean;
      /** Preview Id */
      preview_id?: string | null;
    };
    /** SubmissionCreate */
    SubmissionCreate: {
      /** Value */
      value: string;
      /**
       * Source
       * @enum {string}
       */
      source: 'customer_report' | 'analyst_discovery' | 'automated_discovery';
      /**
       * Note
       * @default
       */
      note: string;
    };
    /** SubmissionView */
    SubmissionView: {
      /** Id */
      id: string;
      /**
       * Source
       * @enum {string}
       */
      source: 'customer_report' | 'analyst_discovery' | 'automated_discovery';
      /** Note */
      note: string;
      target: components['schemas']['TargetView'];
    };
    /** TargetView */
    TargetView: {
      /** Raw Value */
      raw_value: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: 'url' | 'domain' | 'ip' | 'cert' | 'js_hash' | 'favicon_hash';
      /** Canonical Value */
      canonical_value: string;
      /** Hostname */
      hostname?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WatchCreate */
    WatchCreate: {
      /** Entity Id */
      entity_id?: string | null;
      /**
       * Interval Minutes
       * @default 60
       */
      interval_minutes: number;
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
    };
    /** WatchPatch */
    WatchPatch: {
      /** Interval Minutes */
      interval_minutes?: number | null;
      /** Enabled */
      enabled?: boolean | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  local_session_api_session_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  models_api_models_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ModelPage'];
        };
      };
    };
  };
  list_brands_api_brands_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BrandPage'];
        };
      };
    };
  };
  create_brand_api_brands_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BrandCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BrandView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  brand_references_api_brands__brand_id__attachments_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        brand_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  attach_brand_api_brands__brand_id__attachments_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        brand_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_attach_brand_api_brands__brand_id__attachments_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArtifactView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  brand_attachment_api_brands__brand_id__attachments__artifact_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        brand_id: string;
        artifact_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_investigations_api_investigations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InvestigationPage'];
        };
      };
    };
  };
  create_investigation_api_investigations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InvestigationCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InvestigationView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_investigation_api_investigations__investigation_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InvestigationView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  patch_investigation_api_investigations__investigation_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InvestigationPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InvestigationView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_submission_api_investigations__investigation_id__submissions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmissionCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubmissionView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_note_api_investigations__investigation_id__notes_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NoteCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NoteView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_decision_api_investigations__investigation_id__decisions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DecisionCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DecisionView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  attach_investigation_api_investigations__investigation_id__attachments_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_attach_investigation_api_investigations__investigation_id__attachments_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArtifactView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  investigation_attachment_api_investigations__investigation_id__attachments__artifact_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
        artifact_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_job_api_investigations__investigation_id__jobs_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JobCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_job_api_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  cancel_job_api_jobs__job_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  groups_api_investigations__investigation_id__groups_get: {
    parameters: {
      query?: {
        by?: string;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GroupPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  entities_api_investigations__investigation_id__entities_get: {
    parameters: {
      query?: {
        kind?: string | null;
        group_key?: string | null;
        limit?: number;
        cursor?: string | null;
        q?: string;
        has_capture?: boolean;
        shared?: ('javascript' | 'certificate') | null;
        recent_hours?: number | null;
        sort?: 'name' | 'latest' | 'priority';
      };
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntityPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  graph_api_investigations__investigation_id__graph_get: {
    parameters: {
      query?: {
        root_id?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GraphView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  evidence_api_investigations__investigation_id__evidence__evidence_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
        evidence_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EvidenceView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  analyses_api_investigations__investigation_id__analyses_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AnalysisPage'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_analysis_api_investigations__investigation_id__analyses_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AnalysisCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  report_api_investigations__investigation_id__report_get: {
    parameters: {
      query?: {
        format?: 'markdown' | 'json';
        redact?: boolean;
      };
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  evidence_list_api_investigations__investigation_id__evidence_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  captures_api_investigations__investigation_id__captures_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_capture_api_investigations__investigation_id__captures_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CaptureCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  visual_similarity_api_investigations__investigation_id__visual_similarity_get: {
    parameters: {
      query: {
        reference_id: string;
      };
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  candidates_api_investigations__investigation_id__candidates_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  runs_api_investigations__investigation_id__runs_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  changes_api_investigations__investigation_id__changes_get: {
    parameters: {
      query?: {
        before?: string | null;
        after?: string | null;
      };
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  claim_grounding_api_investigations__investigation_id__grounding_get: {
    parameters: {
      query?: {
        analysis_id?: string | null;
      };
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  watch_list_api_investigations__investigation_id__watches_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_watch_api_investigations__investigation_id__watches_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WatchCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  patch_watch_api_investigations__investigation_id__watches__watch_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
        watch_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WatchPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  run_watch_api_investigations__investigation_id__watches__watch_id__run_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
        watch_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_alert_api_investigations__investigation_id__alerts__alert_id__read_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
        alert_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  story_preview_api_investigations__investigation_id__story_preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StoryCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  story_export_api_investigations__investigation_id__story_export_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StoryCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  memory_api_investigations__investigation_id__memory_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  history_api_investigations__investigation_id__assistant_get: {
    parameters: {
      query?: {
        limit?: number;
        before?: string | null;
      };
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  ask_api_investigations__investigation_id__assistant_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssistantRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  preview_api_investigations__investigation_id__replay_preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReplayPreviewRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  export_api_investigations__investigation_id__replay_export_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReplayExportRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_settings_api_settings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IntegrationView'];
        };
      };
    };
  };
  save_settings_api_settings_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['IntegrationPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IntegrationView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  available_models_api_settings_llm_models_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LlmCheck'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AvailableModels'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  test_llm_api_settings_llm_test_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LlmCheck'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConnectionResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  test_source_api_settings_sources_test_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SourceCheck'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConnectionResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
